export const amber = {
	1: "hsl(var(--color-amber-1) / <alpha-value>)",
	2: "hsl(var(--color-amber-2) / <alpha-value>)",
	3: "hsl(var(--color-amber-3) / <alpha-value>)",
	4: "hsl(var(--color-amber-4) / <alpha-value>)",
	5: "hsl(var(--color-amber-5) / <alpha-value>)",
	6: "hsl(var(--color-amber-6) / <alpha-value>)",
	7: "hsl(var(--color-amber-7) / <alpha-value>)",
	8: "hsl(var(--color-amber-8) / <alpha-value>)",
	9: "hsl(var(--color-amber-9) / <alpha-value>)",
	10: "hsl(var(--color-amber-10) / <alpha-value>)",
	11: "hsl(var(--color-amber-11) / <alpha-value>)",
	12: "hsl(var(--color-amber-12) / <alpha-value>)",
};
export const amberA = {
	1: "hsl(var(--color-amberA-1))",
	2: "hsl(var(--color-amberA-2))",
	3: "hsl(var(--color-amberA-3))",
	4: "hsl(var(--color-amberA-4))",
	5: "hsl(var(--color-amberA-5))",
	6: "hsl(var(--color-amberA-6))",
	7: "hsl(var(--color-amberA-7))",
	8: "hsl(var(--color-amberA-8))",
	9: "hsl(var(--color-amberA-9))",
	10: "hsl(var(--color-amberA-10))",
	11: "hsl(var(--color-amberA-11))",
	12: "hsl(var(--color-amberA-12))",
};
export const blackA = {
	1: "hsl(var(--color-blackA-1))",
	2: "hsl(var(--color-blackA-2))",
	3: "hsl(var(--color-blackA-3))",
	4: "hsl(var(--color-blackA-4))",
	5: "hsl(var(--color-blackA-5))",
	6: "hsl(var(--color-blackA-6))",
	7: "hsl(var(--color-blackA-7))",
	8: "hsl(var(--color-blackA-8))",
	9: "hsl(var(--color-blackA-9))",
	10: "hsl(var(--color-blackA-10))",
	11: "hsl(var(--color-blackA-11))",
	12: "hsl(var(--color-blackA-12))",
};
export const blue = {
	1: "hsl(var(--color-blue-1) / <alpha-value>)",
	2: "hsl(var(--color-blue-2) / <alpha-value>)",
	3: "hsl(var(--color-blue-3) / <alpha-value>)",
	4: "hsl(var(--color-blue-4) / <alpha-value>)",
	5: "hsl(var(--color-blue-5) / <alpha-value>)",
	6: "hsl(var(--color-blue-6) / <alpha-value>)",
	7: "hsl(var(--color-blue-7) / <alpha-value>)",
	8: "hsl(var(--color-blue-8) / <alpha-value>)",
	9: "hsl(var(--color-blue-9) / <alpha-value>)",
	10: "hsl(var(--color-blue-10) / <alpha-value>)",
	11: "hsl(var(--color-blue-11) / <alpha-value>)",
	12: "hsl(var(--color-blue-12) / <alpha-value>)",
};
export const blueA = {
	1: "hsl(var(--color-blueA-1))",
	2: "hsl(var(--color-blueA-2))",
	3: "hsl(var(--color-blueA-3))",
	4: "hsl(var(--color-blueA-4))",
	5: "hsl(var(--color-blueA-5))",
	6: "hsl(var(--color-blueA-6))",
	7: "hsl(var(--color-blueA-7))",
	8: "hsl(var(--color-blueA-8))",
	9: "hsl(var(--color-blueA-9))",
	10: "hsl(var(--color-blueA-10))",
	11: "hsl(var(--color-blueA-11))",
	12: "hsl(var(--color-blueA-12))",
};
export const bronze = {
	1: "hsl(var(--color-bronze-1) / <alpha-value>)",
	2: "hsl(var(--color-bronze-2) / <alpha-value>)",
	3: "hsl(var(--color-bronze-3) / <alpha-value>)",
	4: "hsl(var(--color-bronze-4) / <alpha-value>)",
	5: "hsl(var(--color-bronze-5) / <alpha-value>)",
	6: "hsl(var(--color-bronze-6) / <alpha-value>)",
	7: "hsl(var(--color-bronze-7) / <alpha-value>)",
	8: "hsl(var(--color-bronze-8) / <alpha-value>)",
	9: "hsl(var(--color-bronze-9) / <alpha-value>)",
	10: "hsl(var(--color-bronze-10) / <alpha-value>)",
	11: "hsl(var(--color-bronze-11) / <alpha-value>)",
	12: "hsl(var(--color-bronze-12) / <alpha-value>)",
};
export const bronzeA = {
	1: "hsl(var(--color-bronzeA-1))",
	2: "hsl(var(--color-bronzeA-2))",
	3: "hsl(var(--color-bronzeA-3))",
	4: "hsl(var(--color-bronzeA-4))",
	5: "hsl(var(--color-bronzeA-5))",
	6: "hsl(var(--color-bronzeA-6))",
	7: "hsl(var(--color-bronzeA-7))",
	8: "hsl(var(--color-bronzeA-8))",
	9: "hsl(var(--color-bronzeA-9))",
	10: "hsl(var(--color-bronzeA-10))",
	11: "hsl(var(--color-bronzeA-11))",
	12: "hsl(var(--color-bronzeA-12))",
};
export const brown = {
	1: "hsl(var(--color-brown-1) / <alpha-value>)",
	2: "hsl(var(--color-brown-2) / <alpha-value>)",
	3: "hsl(var(--color-brown-3) / <alpha-value>)",
	4: "hsl(var(--color-brown-4) / <alpha-value>)",
	5: "hsl(var(--color-brown-5) / <alpha-value>)",
	6: "hsl(var(--color-brown-6) / <alpha-value>)",
	7: "hsl(var(--color-brown-7) / <alpha-value>)",
	8: "hsl(var(--color-brown-8) / <alpha-value>)",
	9: "hsl(var(--color-brown-9) / <alpha-value>)",
	10: "hsl(var(--color-brown-10) / <alpha-value>)",
	11: "hsl(var(--color-brown-11) / <alpha-value>)",
	12: "hsl(var(--color-brown-12) / <alpha-value>)",
};
export const brownA = {
	1: "hsl(var(--color-brownA-1))",
	2: "hsl(var(--color-brownA-2))",
	3: "hsl(var(--color-brownA-3))",
	4: "hsl(var(--color-brownA-4))",
	5: "hsl(var(--color-brownA-5))",
	6: "hsl(var(--color-brownA-6))",
	7: "hsl(var(--color-brownA-7))",
	8: "hsl(var(--color-brownA-8))",
	9: "hsl(var(--color-brownA-9))",
	10: "hsl(var(--color-brownA-10))",
	11: "hsl(var(--color-brownA-11))",
	12: "hsl(var(--color-brownA-12))",
};
export const crimson = {
	1: "hsl(var(--color-crimson-1) / <alpha-value>)",
	2: "hsl(var(--color-crimson-2) / <alpha-value>)",
	3: "hsl(var(--color-crimson-3) / <alpha-value>)",
	4: "hsl(var(--color-crimson-4) / <alpha-value>)",
	5: "hsl(var(--color-crimson-5) / <alpha-value>)",
	6: "hsl(var(--color-crimson-6) / <alpha-value>)",
	7: "hsl(var(--color-crimson-7) / <alpha-value>)",
	8: "hsl(var(--color-crimson-8) / <alpha-value>)",
	9: "hsl(var(--color-crimson-9) / <alpha-value>)",
	10: "hsl(var(--color-crimson-10) / <alpha-value>)",
	11: "hsl(var(--color-crimson-11) / <alpha-value>)",
	12: "hsl(var(--color-crimson-12) / <alpha-value>)",
};
export const crimsonA = {
	1: "hsl(var(--color-crimsonA-1))",
	2: "hsl(var(--color-crimsonA-2))",
	3: "hsl(var(--color-crimsonA-3))",
	4: "hsl(var(--color-crimsonA-4))",
	5: "hsl(var(--color-crimsonA-5))",
	6: "hsl(var(--color-crimsonA-6))",
	7: "hsl(var(--color-crimsonA-7))",
	8: "hsl(var(--color-crimsonA-8))",
	9: "hsl(var(--color-crimsonA-9))",
	10: "hsl(var(--color-crimsonA-10))",
	11: "hsl(var(--color-crimsonA-11))",
	12: "hsl(var(--color-crimsonA-12))",
};
export const cyan = {
	1: "hsl(var(--color-cyan-1) / <alpha-value>)",
	2: "hsl(var(--color-cyan-2) / <alpha-value>)",
	3: "hsl(var(--color-cyan-3) / <alpha-value>)",
	4: "hsl(var(--color-cyan-4) / <alpha-value>)",
	5: "hsl(var(--color-cyan-5) / <alpha-value>)",
	6: "hsl(var(--color-cyan-6) / <alpha-value>)",
	7: "hsl(var(--color-cyan-7) / <alpha-value>)",
	8: "hsl(var(--color-cyan-8) / <alpha-value>)",
	9: "hsl(var(--color-cyan-9) / <alpha-value>)",
	10: "hsl(var(--color-cyan-10) / <alpha-value>)",
	11: "hsl(var(--color-cyan-11) / <alpha-value>)",
	12: "hsl(var(--color-cyan-12) / <alpha-value>)",
};
export const cyanA = {
	1: "hsl(var(--color-cyanA-1))",
	2: "hsl(var(--color-cyanA-2))",
	3: "hsl(var(--color-cyanA-3))",
	4: "hsl(var(--color-cyanA-4))",
	5: "hsl(var(--color-cyanA-5))",
	6: "hsl(var(--color-cyanA-6))",
	7: "hsl(var(--color-cyanA-7))",
	8: "hsl(var(--color-cyanA-8))",
	9: "hsl(var(--color-cyanA-9))",
	10: "hsl(var(--color-cyanA-10))",
	11: "hsl(var(--color-cyanA-11))",
	12: "hsl(var(--color-cyanA-12))",
};
export const gold = {
	1: "hsl(var(--color-gold-1) / <alpha-value>)",
	2: "hsl(var(--color-gold-2) / <alpha-value>)",
	3: "hsl(var(--color-gold-3) / <alpha-value>)",
	4: "hsl(var(--color-gold-4) / <alpha-value>)",
	5: "hsl(var(--color-gold-5) / <alpha-value>)",
	6: "hsl(var(--color-gold-6) / <alpha-value>)",
	7: "hsl(var(--color-gold-7) / <alpha-value>)",
	8: "hsl(var(--color-gold-8) / <alpha-value>)",
	9: "hsl(var(--color-gold-9) / <alpha-value>)",
	10: "hsl(var(--color-gold-10) / <alpha-value>)",
	11: "hsl(var(--color-gold-11) / <alpha-value>)",
	12: "hsl(var(--color-gold-12) / <alpha-value>)",
};
export const goldA = {
	1: "hsl(var(--color-goldA-1))",
	2: "hsl(var(--color-goldA-2))",
	3: "hsl(var(--color-goldA-3))",
	4: "hsl(var(--color-goldA-4))",
	5: "hsl(var(--color-goldA-5))",
	6: "hsl(var(--color-goldA-6))",
	7: "hsl(var(--color-goldA-7))",
	8: "hsl(var(--color-goldA-8))",
	9: "hsl(var(--color-goldA-9))",
	10: "hsl(var(--color-goldA-10))",
	11: "hsl(var(--color-goldA-11))",
	12: "hsl(var(--color-goldA-12))",
};
export const grass = {
	1: "hsl(var(--color-grass-1) / <alpha-value>)",
	2: "hsl(var(--color-grass-2) / <alpha-value>)",
	3: "hsl(var(--color-grass-3) / <alpha-value>)",
	4: "hsl(var(--color-grass-4) / <alpha-value>)",
	5: "hsl(var(--color-grass-5) / <alpha-value>)",
	6: "hsl(var(--color-grass-6) / <alpha-value>)",
	7: "hsl(var(--color-grass-7) / <alpha-value>)",
	8: "hsl(var(--color-grass-8) / <alpha-value>)",
	9: "hsl(var(--color-grass-9) / <alpha-value>)",
	10: "hsl(var(--color-grass-10) / <alpha-value>)",
	11: "hsl(var(--color-grass-11) / <alpha-value>)",
	12: "hsl(var(--color-grass-12) / <alpha-value>)",
};
export const grassA = {
	1: "hsl(var(--color-grassA-1))",
	2: "hsl(var(--color-grassA-2))",
	3: "hsl(var(--color-grassA-3))",
	4: "hsl(var(--color-grassA-4))",
	5: "hsl(var(--color-grassA-5))",
	6: "hsl(var(--color-grassA-6))",
	7: "hsl(var(--color-grassA-7))",
	8: "hsl(var(--color-grassA-8))",
	9: "hsl(var(--color-grassA-9))",
	10: "hsl(var(--color-grassA-10))",
	11: "hsl(var(--color-grassA-11))",
	12: "hsl(var(--color-grassA-12))",
};
export const gray = {
	1: "hsl(var(--color-gray-1) / <alpha-value>)",
	2: "hsl(var(--color-gray-2) / <alpha-value>)",
	3: "hsl(var(--color-gray-3) / <alpha-value>)",
	4: "hsl(var(--color-gray-4) / <alpha-value>)",
	5: "hsl(var(--color-gray-5) / <alpha-value>)",
	6: "hsl(var(--color-gray-6) / <alpha-value>)",
	7: "hsl(var(--color-gray-7) / <alpha-value>)",
	8: "hsl(var(--color-gray-8) / <alpha-value>)",
	9: "hsl(var(--color-gray-9) / <alpha-value>)",
	10: "hsl(var(--color-gray-10) / <alpha-value>)",
	11: "hsl(var(--color-gray-11) / <alpha-value>)",
	12: "hsl(var(--color-gray-12) / <alpha-value>)",
};
export const grayA = {
	1: "hsl(var(--color-grayA-1))",
	2: "hsl(var(--color-grayA-2))",
	3: "hsl(var(--color-grayA-3))",
	4: "hsl(var(--color-grayA-4))",
	5: "hsl(var(--color-grayA-5))",
	6: "hsl(var(--color-grayA-6))",
	7: "hsl(var(--color-grayA-7))",
	8: "hsl(var(--color-grayA-8))",
	9: "hsl(var(--color-grayA-9))",
	10: "hsl(var(--color-grayA-10))",
	11: "hsl(var(--color-grayA-11))",
	12: "hsl(var(--color-grayA-12))",
};
export const green = {
	1: "hsl(var(--color-green-1) / <alpha-value>)",
	2: "hsl(var(--color-green-2) / <alpha-value>)",
	3: "hsl(var(--color-green-3) / <alpha-value>)",
	4: "hsl(var(--color-green-4) / <alpha-value>)",
	5: "hsl(var(--color-green-5) / <alpha-value>)",
	6: "hsl(var(--color-green-6) / <alpha-value>)",
	7: "hsl(var(--color-green-7) / <alpha-value>)",
	8: "hsl(var(--color-green-8) / <alpha-value>)",
	9: "hsl(var(--color-green-9) / <alpha-value>)",
	10: "hsl(var(--color-green-10) / <alpha-value>)",
	11: "hsl(var(--color-green-11) / <alpha-value>)",
	12: "hsl(var(--color-green-12) / <alpha-value>)",
};
export const greenA = {
	1: "hsl(var(--color-greenA-1))",
	2: "hsl(var(--color-greenA-2))",
	3: "hsl(var(--color-greenA-3))",
	4: "hsl(var(--color-greenA-4))",
	5: "hsl(var(--color-greenA-5))",
	6: "hsl(var(--color-greenA-6))",
	7: "hsl(var(--color-greenA-7))",
	8: "hsl(var(--color-greenA-8))",
	9: "hsl(var(--color-greenA-9))",
	10: "hsl(var(--color-greenA-10))",
	11: "hsl(var(--color-greenA-11))",
	12: "hsl(var(--color-greenA-12))",
};
export const indigo = {
	1: "hsl(var(--color-indigo-1) / <alpha-value>)",
	2: "hsl(var(--color-indigo-2) / <alpha-value>)",
	3: "hsl(var(--color-indigo-3) / <alpha-value>)",
	4: "hsl(var(--color-indigo-4) / <alpha-value>)",
	5: "hsl(var(--color-indigo-5) / <alpha-value>)",
	6: "hsl(var(--color-indigo-6) / <alpha-value>)",
	7: "hsl(var(--color-indigo-7) / <alpha-value>)",
	8: "hsl(var(--color-indigo-8) / <alpha-value>)",
	9: "hsl(var(--color-indigo-9) / <alpha-value>)",
	10: "hsl(var(--color-indigo-10) / <alpha-value>)",
	11: "hsl(var(--color-indigo-11) / <alpha-value>)",
	12: "hsl(var(--color-indigo-12) / <alpha-value>)",
};
export const indigoA = {
	1: "hsl(var(--color-indigoA-1))",
	2: "hsl(var(--color-indigoA-2))",
	3: "hsl(var(--color-indigoA-3))",
	4: "hsl(var(--color-indigoA-4))",
	5: "hsl(var(--color-indigoA-5))",
	6: "hsl(var(--color-indigoA-6))",
	7: "hsl(var(--color-indigoA-7))",
	8: "hsl(var(--color-indigoA-8))",
	9: "hsl(var(--color-indigoA-9))",
	10: "hsl(var(--color-indigoA-10))",
	11: "hsl(var(--color-indigoA-11))",
	12: "hsl(var(--color-indigoA-12))",
};
export const iris = {
	1: "hsl(var(--color-iris-1) / <alpha-value>)",
	2: "hsl(var(--color-iris-2) / <alpha-value>)",
	3: "hsl(var(--color-iris-3) / <alpha-value>)",
	4: "hsl(var(--color-iris-4) / <alpha-value>)",
	5: "hsl(var(--color-iris-5) / <alpha-value>)",
	6: "hsl(var(--color-iris-6) / <alpha-value>)",
	7: "hsl(var(--color-iris-7) / <alpha-value>)",
	8: "hsl(var(--color-iris-8) / <alpha-value>)",
	9: "hsl(var(--color-iris-9) / <alpha-value>)",
	10: "hsl(var(--color-iris-10) / <alpha-value>)",
	11: "hsl(var(--color-iris-11) / <alpha-value>)",
	12: "hsl(var(--color-iris-12) / <alpha-value>)",
};
export const irisA = {
	1: "hsl(var(--color-irisA-1))",
	2: "hsl(var(--color-irisA-2))",
	3: "hsl(var(--color-irisA-3))",
	4: "hsl(var(--color-irisA-4))",
	5: "hsl(var(--color-irisA-5))",
	6: "hsl(var(--color-irisA-6))",
	7: "hsl(var(--color-irisA-7))",
	8: "hsl(var(--color-irisA-8))",
	9: "hsl(var(--color-irisA-9))",
	10: "hsl(var(--color-irisA-10))",
	11: "hsl(var(--color-irisA-11))",
	12: "hsl(var(--color-irisA-12))",
};
export const jade = {
	1: "hsl(var(--color-jade-1) / <alpha-value>)",
	2: "hsl(var(--color-jade-2) / <alpha-value>)",
	3: "hsl(var(--color-jade-3) / <alpha-value>)",
	4: "hsl(var(--color-jade-4) / <alpha-value>)",
	5: "hsl(var(--color-jade-5) / <alpha-value>)",
	6: "hsl(var(--color-jade-6) / <alpha-value>)",
	7: "hsl(var(--color-jade-7) / <alpha-value>)",
	8: "hsl(var(--color-jade-8) / <alpha-value>)",
	9: "hsl(var(--color-jade-9) / <alpha-value>)",
	10: "hsl(var(--color-jade-10) / <alpha-value>)",
	11: "hsl(var(--color-jade-11) / <alpha-value>)",
	12: "hsl(var(--color-jade-12) / <alpha-value>)",
};
export const jadeA = {
	1: "hsl(var(--color-jadeA-1))",
	2: "hsl(var(--color-jadeA-2))",
	3: "hsl(var(--color-jadeA-3))",
	4: "hsl(var(--color-jadeA-4))",
	5: "hsl(var(--color-jadeA-5))",
	6: "hsl(var(--color-jadeA-6))",
	7: "hsl(var(--color-jadeA-7))",
	8: "hsl(var(--color-jadeA-8))",
	9: "hsl(var(--color-jadeA-9))",
	10: "hsl(var(--color-jadeA-10))",
	11: "hsl(var(--color-jadeA-11))",
	12: "hsl(var(--color-jadeA-12))",
};
export const lime = {
	1: "hsl(var(--color-lime-1) / <alpha-value>)",
	2: "hsl(var(--color-lime-2) / <alpha-value>)",
	3: "hsl(var(--color-lime-3) / <alpha-value>)",
	4: "hsl(var(--color-lime-4) / <alpha-value>)",
	5: "hsl(var(--color-lime-5) / <alpha-value>)",
	6: "hsl(var(--color-lime-6) / <alpha-value>)",
	7: "hsl(var(--color-lime-7) / <alpha-value>)",
	8: "hsl(var(--color-lime-8) / <alpha-value>)",
	9: "hsl(var(--color-lime-9) / <alpha-value>)",
	10: "hsl(var(--color-lime-10) / <alpha-value>)",
	11: "hsl(var(--color-lime-11) / <alpha-value>)",
	12: "hsl(var(--color-lime-12) / <alpha-value>)",
};
export const limeA = {
	1: "hsl(var(--color-limeA-1))",
	2: "hsl(var(--color-limeA-2))",
	3: "hsl(var(--color-limeA-3))",
	4: "hsl(var(--color-limeA-4))",
	5: "hsl(var(--color-limeA-5))",
	6: "hsl(var(--color-limeA-6))",
	7: "hsl(var(--color-limeA-7))",
	8: "hsl(var(--color-limeA-8))",
	9: "hsl(var(--color-limeA-9))",
	10: "hsl(var(--color-limeA-10))",
	11: "hsl(var(--color-limeA-11))",
	12: "hsl(var(--color-limeA-12))",
};
export const mauve = {
	1: "hsl(var(--color-mauve-1) / <alpha-value>)",
	2: "hsl(var(--color-mauve-2) / <alpha-value>)",
	3: "hsl(var(--color-mauve-3) / <alpha-value>)",
	4: "hsl(var(--color-mauve-4) / <alpha-value>)",
	5: "hsl(var(--color-mauve-5) / <alpha-value>)",
	6: "hsl(var(--color-mauve-6) / <alpha-value>)",
	7: "hsl(var(--color-mauve-7) / <alpha-value>)",
	8: "hsl(var(--color-mauve-8) / <alpha-value>)",
	9: "hsl(var(--color-mauve-9) / <alpha-value>)",
	10: "hsl(var(--color-mauve-10) / <alpha-value>)",
	11: "hsl(var(--color-mauve-11) / <alpha-value>)",
	12: "hsl(var(--color-mauve-12) / <alpha-value>)",
};
export const mauveA = {
	1: "hsl(var(--color-mauveA-1))",
	2: "hsl(var(--color-mauveA-2))",
	3: "hsl(var(--color-mauveA-3))",
	4: "hsl(var(--color-mauveA-4))",
	5: "hsl(var(--color-mauveA-5))",
	6: "hsl(var(--color-mauveA-6))",
	7: "hsl(var(--color-mauveA-7))",
	8: "hsl(var(--color-mauveA-8))",
	9: "hsl(var(--color-mauveA-9))",
	10: "hsl(var(--color-mauveA-10))",
	11: "hsl(var(--color-mauveA-11))",
	12: "hsl(var(--color-mauveA-12))",
};
export const mint = {
	1: "hsl(var(--color-mint-1) / <alpha-value>)",
	2: "hsl(var(--color-mint-2) / <alpha-value>)",
	3: "hsl(var(--color-mint-3) / <alpha-value>)",
	4: "hsl(var(--color-mint-4) / <alpha-value>)",
	5: "hsl(var(--color-mint-5) / <alpha-value>)",
	6: "hsl(var(--color-mint-6) / <alpha-value>)",
	7: "hsl(var(--color-mint-7) / <alpha-value>)",
	8: "hsl(var(--color-mint-8) / <alpha-value>)",
	9: "hsl(var(--color-mint-9) / <alpha-value>)",
	10: "hsl(var(--color-mint-10) / <alpha-value>)",
	11: "hsl(var(--color-mint-11) / <alpha-value>)",
	12: "hsl(var(--color-mint-12) / <alpha-value>)",
};
export const mintA = {
	1: "hsl(var(--color-mintA-1))",
	2: "hsl(var(--color-mintA-2))",
	3: "hsl(var(--color-mintA-3))",
	4: "hsl(var(--color-mintA-4))",
	5: "hsl(var(--color-mintA-5))",
	6: "hsl(var(--color-mintA-6))",
	7: "hsl(var(--color-mintA-7))",
	8: "hsl(var(--color-mintA-8))",
	9: "hsl(var(--color-mintA-9))",
	10: "hsl(var(--color-mintA-10))",
	11: "hsl(var(--color-mintA-11))",
	12: "hsl(var(--color-mintA-12))",
};
export const olive = {
	1: "hsl(var(--color-olive-1) / <alpha-value>)",
	2: "hsl(var(--color-olive-2) / <alpha-value>)",
	3: "hsl(var(--color-olive-3) / <alpha-value>)",
	4: "hsl(var(--color-olive-4) / <alpha-value>)",
	5: "hsl(var(--color-olive-5) / <alpha-value>)",
	6: "hsl(var(--color-olive-6) / <alpha-value>)",
	7: "hsl(var(--color-olive-7) / <alpha-value>)",
	8: "hsl(var(--color-olive-8) / <alpha-value>)",
	9: "hsl(var(--color-olive-9) / <alpha-value>)",
	10: "hsl(var(--color-olive-10) / <alpha-value>)",
	11: "hsl(var(--color-olive-11) / <alpha-value>)",
	12: "hsl(var(--color-olive-12) / <alpha-value>)",
};
export const oliveA = {
	1: "hsl(var(--color-oliveA-1))",
	2: "hsl(var(--color-oliveA-2))",
	3: "hsl(var(--color-oliveA-3))",
	4: "hsl(var(--color-oliveA-4))",
	5: "hsl(var(--color-oliveA-5))",
	6: "hsl(var(--color-oliveA-6))",
	7: "hsl(var(--color-oliveA-7))",
	8: "hsl(var(--color-oliveA-8))",
	9: "hsl(var(--color-oliveA-9))",
	10: "hsl(var(--color-oliveA-10))",
	11: "hsl(var(--color-oliveA-11))",
	12: "hsl(var(--color-oliveA-12))",
};
export const orange = {
	1: "hsl(var(--color-orange-1) / <alpha-value>)",
	2: "hsl(var(--color-orange-2) / <alpha-value>)",
	3: "hsl(var(--color-orange-3) / <alpha-value>)",
	4: "hsl(var(--color-orange-4) / <alpha-value>)",
	5: "hsl(var(--color-orange-5) / <alpha-value>)",
	6: "hsl(var(--color-orange-6) / <alpha-value>)",
	7: "hsl(var(--color-orange-7) / <alpha-value>)",
	8: "hsl(var(--color-orange-8) / <alpha-value>)",
	9: "hsl(var(--color-orange-9) / <alpha-value>)",
	10: "hsl(var(--color-orange-10) / <alpha-value>)",
	11: "hsl(var(--color-orange-11) / <alpha-value>)",
	12: "hsl(var(--color-orange-12) / <alpha-value>)",
};
export const orangeA = {
	1: "hsl(var(--color-orangeA-1))",
	2: "hsl(var(--color-orangeA-2))",
	3: "hsl(var(--color-orangeA-3))",
	4: "hsl(var(--color-orangeA-4))",
	5: "hsl(var(--color-orangeA-5))",
	6: "hsl(var(--color-orangeA-6))",
	7: "hsl(var(--color-orangeA-7))",
	8: "hsl(var(--color-orangeA-8))",
	9: "hsl(var(--color-orangeA-9))",
	10: "hsl(var(--color-orangeA-10))",
	11: "hsl(var(--color-orangeA-11))",
	12: "hsl(var(--color-orangeA-12))",
};
export const pink = {
	1: "hsl(var(--color-pink-1) / <alpha-value>)",
	2: "hsl(var(--color-pink-2) / <alpha-value>)",
	3: "hsl(var(--color-pink-3) / <alpha-value>)",
	4: "hsl(var(--color-pink-4) / <alpha-value>)",
	5: "hsl(var(--color-pink-5) / <alpha-value>)",
	6: "hsl(var(--color-pink-6) / <alpha-value>)",
	7: "hsl(var(--color-pink-7) / <alpha-value>)",
	8: "hsl(var(--color-pink-8) / <alpha-value>)",
	9: "hsl(var(--color-pink-9) / <alpha-value>)",
	10: "hsl(var(--color-pink-10) / <alpha-value>)",
	11: "hsl(var(--color-pink-11) / <alpha-value>)",
	12: "hsl(var(--color-pink-12) / <alpha-value>)",
};
export const pinkA = {
	1: "hsl(var(--color-pinkA-1))",
	2: "hsl(var(--color-pinkA-2))",
	3: "hsl(var(--color-pinkA-3))",
	4: "hsl(var(--color-pinkA-4))",
	5: "hsl(var(--color-pinkA-5))",
	6: "hsl(var(--color-pinkA-6))",
	7: "hsl(var(--color-pinkA-7))",
	8: "hsl(var(--color-pinkA-8))",
	9: "hsl(var(--color-pinkA-9))",
	10: "hsl(var(--color-pinkA-10))",
	11: "hsl(var(--color-pinkA-11))",
	12: "hsl(var(--color-pinkA-12))",
};
export const plum = {
	1: "hsl(var(--color-plum-1) / <alpha-value>)",
	2: "hsl(var(--color-plum-2) / <alpha-value>)",
	3: "hsl(var(--color-plum-3) / <alpha-value>)",
	4: "hsl(var(--color-plum-4) / <alpha-value>)",
	5: "hsl(var(--color-plum-5) / <alpha-value>)",
	6: "hsl(var(--color-plum-6) / <alpha-value>)",
	7: "hsl(var(--color-plum-7) / <alpha-value>)",
	8: "hsl(var(--color-plum-8) / <alpha-value>)",
	9: "hsl(var(--color-plum-9) / <alpha-value>)",
	10: "hsl(var(--color-plum-10) / <alpha-value>)",
	11: "hsl(var(--color-plum-11) / <alpha-value>)",
	12: "hsl(var(--color-plum-12) / <alpha-value>)",
};
export const plumA = {
	1: "hsl(var(--color-plumA-1))",
	2: "hsl(var(--color-plumA-2))",
	3: "hsl(var(--color-plumA-3))",
	4: "hsl(var(--color-plumA-4))",
	5: "hsl(var(--color-plumA-5))",
	6: "hsl(var(--color-plumA-6))",
	7: "hsl(var(--color-plumA-7))",
	8: "hsl(var(--color-plumA-8))",
	9: "hsl(var(--color-plumA-9))",
	10: "hsl(var(--color-plumA-10))",
	11: "hsl(var(--color-plumA-11))",
	12: "hsl(var(--color-plumA-12))",
};
export const purple = {
	1: "hsl(var(--color-purple-1) / <alpha-value>)",
	2: "hsl(var(--color-purple-2) / <alpha-value>)",
	3: "hsl(var(--color-purple-3) / <alpha-value>)",
	4: "hsl(var(--color-purple-4) / <alpha-value>)",
	5: "hsl(var(--color-purple-5) / <alpha-value>)",
	6: "hsl(var(--color-purple-6) / <alpha-value>)",
	7: "hsl(var(--color-purple-7) / <alpha-value>)",
	8: "hsl(var(--color-purple-8) / <alpha-value>)",
	9: "hsl(var(--color-purple-9) / <alpha-value>)",
	10: "hsl(var(--color-purple-10) / <alpha-value>)",
	11: "hsl(var(--color-purple-11) / <alpha-value>)",
	12: "hsl(var(--color-purple-12) / <alpha-value>)",
};
export const purpleA = {
	1: "hsl(var(--color-purpleA-1))",
	2: "hsl(var(--color-purpleA-2))",
	3: "hsl(var(--color-purpleA-3))",
	4: "hsl(var(--color-purpleA-4))",
	5: "hsl(var(--color-purpleA-5))",
	6: "hsl(var(--color-purpleA-6))",
	7: "hsl(var(--color-purpleA-7))",
	8: "hsl(var(--color-purpleA-8))",
	9: "hsl(var(--color-purpleA-9))",
	10: "hsl(var(--color-purpleA-10))",
	11: "hsl(var(--color-purpleA-11))",
	12: "hsl(var(--color-purpleA-12))",
};
export const red = {
	1: "hsl(var(--color-red-1) / <alpha-value>)",
	2: "hsl(var(--color-red-2) / <alpha-value>)",
	3: "hsl(var(--color-red-3) / <alpha-value>)",
	4: "hsl(var(--color-red-4) / <alpha-value>)",
	5: "hsl(var(--color-red-5) / <alpha-value>)",
	6: "hsl(var(--color-red-6) / <alpha-value>)",
	7: "hsl(var(--color-red-7) / <alpha-value>)",
	8: "hsl(var(--color-red-8) / <alpha-value>)",
	9: "hsl(var(--color-red-9) / <alpha-value>)",
	10: "hsl(var(--color-red-10) / <alpha-value>)",
	11: "hsl(var(--color-red-11) / <alpha-value>)",
	12: "hsl(var(--color-red-12) / <alpha-value>)",
};
export const redA = {
	1: "hsl(var(--color-redA-1))",
	2: "hsl(var(--color-redA-2))",
	3: "hsl(var(--color-redA-3))",
	4: "hsl(var(--color-redA-4))",
	5: "hsl(var(--color-redA-5))",
	6: "hsl(var(--color-redA-6))",
	7: "hsl(var(--color-redA-7))",
	8: "hsl(var(--color-redA-8))",
	9: "hsl(var(--color-redA-9))",
	10: "hsl(var(--color-redA-10))",
	11: "hsl(var(--color-redA-11))",
	12: "hsl(var(--color-redA-12))",
};
export const ruby = {
	1: "hsl(var(--color-ruby-1) / <alpha-value>)",
	2: "hsl(var(--color-ruby-2) / <alpha-value>)",
	3: "hsl(var(--color-ruby-3) / <alpha-value>)",
	4: "hsl(var(--color-ruby-4) / <alpha-value>)",
	5: "hsl(var(--color-ruby-5) / <alpha-value>)",
	6: "hsl(var(--color-ruby-6) / <alpha-value>)",
	7: "hsl(var(--color-ruby-7) / <alpha-value>)",
	8: "hsl(var(--color-ruby-8) / <alpha-value>)",
	9: "hsl(var(--color-ruby-9) / <alpha-value>)",
	10: "hsl(var(--color-ruby-10) / <alpha-value>)",
	11: "hsl(var(--color-ruby-11) / <alpha-value>)",
	12: "hsl(var(--color-ruby-12) / <alpha-value>)",
};
export const rubyA = {
	1: "hsl(var(--color-rubyA-1))",
	2: "hsl(var(--color-rubyA-2))",
	3: "hsl(var(--color-rubyA-3))",
	4: "hsl(var(--color-rubyA-4))",
	5: "hsl(var(--color-rubyA-5))",
	6: "hsl(var(--color-rubyA-6))",
	7: "hsl(var(--color-rubyA-7))",
	8: "hsl(var(--color-rubyA-8))",
	9: "hsl(var(--color-rubyA-9))",
	10: "hsl(var(--color-rubyA-10))",
	11: "hsl(var(--color-rubyA-11))",
	12: "hsl(var(--color-rubyA-12))",
};
export const sage = {
	1: "hsl(var(--color-sage-1) / <alpha-value>)",
	2: "hsl(var(--color-sage-2) / <alpha-value>)",
	3: "hsl(var(--color-sage-3) / <alpha-value>)",
	4: "hsl(var(--color-sage-4) / <alpha-value>)",
	5: "hsl(var(--color-sage-5) / <alpha-value>)",
	6: "hsl(var(--color-sage-6) / <alpha-value>)",
	7: "hsl(var(--color-sage-7) / <alpha-value>)",
	8: "hsl(var(--color-sage-8) / <alpha-value>)",
	9: "hsl(var(--color-sage-9) / <alpha-value>)",
	10: "hsl(var(--color-sage-10) / <alpha-value>)",
	11: "hsl(var(--color-sage-11) / <alpha-value>)",
	12: "hsl(var(--color-sage-12) / <alpha-value>)",
};
export const sageA = {
	1: "hsl(var(--color-sageA-1))",
	2: "hsl(var(--color-sageA-2))",
	3: "hsl(var(--color-sageA-3))",
	4: "hsl(var(--color-sageA-4))",
	5: "hsl(var(--color-sageA-5))",
	6: "hsl(var(--color-sageA-6))",
	7: "hsl(var(--color-sageA-7))",
	8: "hsl(var(--color-sageA-8))",
	9: "hsl(var(--color-sageA-9))",
	10: "hsl(var(--color-sageA-10))",
	11: "hsl(var(--color-sageA-11))",
	12: "hsl(var(--color-sageA-12))",
};
export const sand = {
	1: "hsl(var(--color-sand-1) / <alpha-value>)",
	2: "hsl(var(--color-sand-2) / <alpha-value>)",
	3: "hsl(var(--color-sand-3) / <alpha-value>)",
	4: "hsl(var(--color-sand-4) / <alpha-value>)",
	5: "hsl(var(--color-sand-5) / <alpha-value>)",
	6: "hsl(var(--color-sand-6) / <alpha-value>)",
	7: "hsl(var(--color-sand-7) / <alpha-value>)",
	8: "hsl(var(--color-sand-8) / <alpha-value>)",
	9: "hsl(var(--color-sand-9) / <alpha-value>)",
	10: "hsl(var(--color-sand-10) / <alpha-value>)",
	11: "hsl(var(--color-sand-11) / <alpha-value>)",
	12: "hsl(var(--color-sand-12) / <alpha-value>)",
};
export const sandA = {
	1: "hsl(var(--color-sandA-1))",
	2: "hsl(var(--color-sandA-2))",
	3: "hsl(var(--color-sandA-3))",
	4: "hsl(var(--color-sandA-4))",
	5: "hsl(var(--color-sandA-5))",
	6: "hsl(var(--color-sandA-6))",
	7: "hsl(var(--color-sandA-7))",
	8: "hsl(var(--color-sandA-8))",
	9: "hsl(var(--color-sandA-9))",
	10: "hsl(var(--color-sandA-10))",
	11: "hsl(var(--color-sandA-11))",
	12: "hsl(var(--color-sandA-12))",
};
export const sky = {
	1: "hsl(var(--color-sky-1) / <alpha-value>)",
	2: "hsl(var(--color-sky-2) / <alpha-value>)",
	3: "hsl(var(--color-sky-3) / <alpha-value>)",
	4: "hsl(var(--color-sky-4) / <alpha-value>)",
	5: "hsl(var(--color-sky-5) / <alpha-value>)",
	6: "hsl(var(--color-sky-6) / <alpha-value>)",
	7: "hsl(var(--color-sky-7) / <alpha-value>)",
	8: "hsl(var(--color-sky-8) / <alpha-value>)",
	9: "hsl(var(--color-sky-9) / <alpha-value>)",
	10: "hsl(var(--color-sky-10) / <alpha-value>)",
	11: "hsl(var(--color-sky-11) / <alpha-value>)",
	12: "hsl(var(--color-sky-12) / <alpha-value>)",
};
export const skyA = {
	1: "hsl(var(--color-skyA-1))",
	2: "hsl(var(--color-skyA-2))",
	3: "hsl(var(--color-skyA-3))",
	4: "hsl(var(--color-skyA-4))",
	5: "hsl(var(--color-skyA-5))",
	6: "hsl(var(--color-skyA-6))",
	7: "hsl(var(--color-skyA-7))",
	8: "hsl(var(--color-skyA-8))",
	9: "hsl(var(--color-skyA-9))",
	10: "hsl(var(--color-skyA-10))",
	11: "hsl(var(--color-skyA-11))",
	12: "hsl(var(--color-skyA-12))",
};
export const slate = {
	1: "hsl(var(--color-slate-1) / <alpha-value>)",
	2: "hsl(var(--color-slate-2) / <alpha-value>)",
	3: "hsl(var(--color-slate-3) / <alpha-value>)",
	4: "hsl(var(--color-slate-4) / <alpha-value>)",
	5: "hsl(var(--color-slate-5) / <alpha-value>)",
	6: "hsl(var(--color-slate-6) / <alpha-value>)",
	7: "hsl(var(--color-slate-7) / <alpha-value>)",
	8: "hsl(var(--color-slate-8) / <alpha-value>)",
	9: "hsl(var(--color-slate-9) / <alpha-value>)",
	10: "hsl(var(--color-slate-10) / <alpha-value>)",
	11: "hsl(var(--color-slate-11) / <alpha-value>)",
	12: "hsl(var(--color-slate-12) / <alpha-value>)",
};
export const slateA = {
	1: "hsl(var(--color-slateA-1))",
	2: "hsl(var(--color-slateA-2))",
	3: "hsl(var(--color-slateA-3))",
	4: "hsl(var(--color-slateA-4))",
	5: "hsl(var(--color-slateA-5))",
	6: "hsl(var(--color-slateA-6))",
	7: "hsl(var(--color-slateA-7))",
	8: "hsl(var(--color-slateA-8))",
	9: "hsl(var(--color-slateA-9))",
	10: "hsl(var(--color-slateA-10))",
	11: "hsl(var(--color-slateA-11))",
	12: "hsl(var(--color-slateA-12))",
};
export const teal = {
	1: "hsl(var(--color-teal-1) / <alpha-value>)",
	2: "hsl(var(--color-teal-2) / <alpha-value>)",
	3: "hsl(var(--color-teal-3) / <alpha-value>)",
	4: "hsl(var(--color-teal-4) / <alpha-value>)",
	5: "hsl(var(--color-teal-5) / <alpha-value>)",
	6: "hsl(var(--color-teal-6) / <alpha-value>)",
	7: "hsl(var(--color-teal-7) / <alpha-value>)",
	8: "hsl(var(--color-teal-8) / <alpha-value>)",
	9: "hsl(var(--color-teal-9) / <alpha-value>)",
	10: "hsl(var(--color-teal-10) / <alpha-value>)",
	11: "hsl(var(--color-teal-11) / <alpha-value>)",
	12: "hsl(var(--color-teal-12) / <alpha-value>)",
};
export const tealA = {
	1: "hsl(var(--color-tealA-1))",
	2: "hsl(var(--color-tealA-2))",
	3: "hsl(var(--color-tealA-3))",
	4: "hsl(var(--color-tealA-4))",
	5: "hsl(var(--color-tealA-5))",
	6: "hsl(var(--color-tealA-6))",
	7: "hsl(var(--color-tealA-7))",
	8: "hsl(var(--color-tealA-8))",
	9: "hsl(var(--color-tealA-9))",
	10: "hsl(var(--color-tealA-10))",
	11: "hsl(var(--color-tealA-11))",
	12: "hsl(var(--color-tealA-12))",
};
export const tomato = {
	1: "hsl(var(--color-tomato-1) / <alpha-value>)",
	2: "hsl(var(--color-tomato-2) / <alpha-value>)",
	3: "hsl(var(--color-tomato-3) / <alpha-value>)",
	4: "hsl(var(--color-tomato-4) / <alpha-value>)",
	5: "hsl(var(--color-tomato-5) / <alpha-value>)",
	6: "hsl(var(--color-tomato-6) / <alpha-value>)",
	7: "hsl(var(--color-tomato-7) / <alpha-value>)",
	8: "hsl(var(--color-tomato-8) / <alpha-value>)",
	9: "hsl(var(--color-tomato-9) / <alpha-value>)",
	10: "hsl(var(--color-tomato-10) / <alpha-value>)",
	11: "hsl(var(--color-tomato-11) / <alpha-value>)",
	12: "hsl(var(--color-tomato-12) / <alpha-value>)",
};
export const tomatoA = {
	1: "hsl(var(--color-tomatoA-1))",
	2: "hsl(var(--color-tomatoA-2))",
	3: "hsl(var(--color-tomatoA-3))",
	4: "hsl(var(--color-tomatoA-4))",
	5: "hsl(var(--color-tomatoA-5))",
	6: "hsl(var(--color-tomatoA-6))",
	7: "hsl(var(--color-tomatoA-7))",
	8: "hsl(var(--color-tomatoA-8))",
	9: "hsl(var(--color-tomatoA-9))",
	10: "hsl(var(--color-tomatoA-10))",
	11: "hsl(var(--color-tomatoA-11))",
	12: "hsl(var(--color-tomatoA-12))",
};
export const violet = {
	1: "hsl(var(--color-violet-1) / <alpha-value>)",
	2: "hsl(var(--color-violet-2) / <alpha-value>)",
	3: "hsl(var(--color-violet-3) / <alpha-value>)",
	4: "hsl(var(--color-violet-4) / <alpha-value>)",
	5: "hsl(var(--color-violet-5) / <alpha-value>)",
	6: "hsl(var(--color-violet-6) / <alpha-value>)",
	7: "hsl(var(--color-violet-7) / <alpha-value>)",
	8: "hsl(var(--color-violet-8) / <alpha-value>)",
	9: "hsl(var(--color-violet-9) / <alpha-value>)",
	10: "hsl(var(--color-violet-10) / <alpha-value>)",
	11: "hsl(var(--color-violet-11) / <alpha-value>)",
	12: "hsl(var(--color-violet-12) / <alpha-value>)",
};
export const violetA = {
	1: "hsl(var(--color-violetA-1))",
	2: "hsl(var(--color-violetA-2))",
	3: "hsl(var(--color-violetA-3))",
	4: "hsl(var(--color-violetA-4))",
	5: "hsl(var(--color-violetA-5))",
	6: "hsl(var(--color-violetA-6))",
	7: "hsl(var(--color-violetA-7))",
	8: "hsl(var(--color-violetA-8))",
	9: "hsl(var(--color-violetA-9))",
	10: "hsl(var(--color-violetA-10))",
	11: "hsl(var(--color-violetA-11))",
	12: "hsl(var(--color-violetA-12))",
};
export const whiteA = {
	1: "hsl(var(--color-whiteA-1))",
	2: "hsl(var(--color-whiteA-2))",
	3: "hsl(var(--color-whiteA-3))",
	4: "hsl(var(--color-whiteA-4))",
	5: "hsl(var(--color-whiteA-5))",
	6: "hsl(var(--color-whiteA-6))",
	7: "hsl(var(--color-whiteA-7))",
	8: "hsl(var(--color-whiteA-8))",
	9: "hsl(var(--color-whiteA-9))",
	10: "hsl(var(--color-whiteA-10))",
	11: "hsl(var(--color-whiteA-11))",
	12: "hsl(var(--color-whiteA-12))",
};
export const yellow = {
	1: "hsl(var(--color-yellow-1) / <alpha-value>)",
	2: "hsl(var(--color-yellow-2) / <alpha-value>)",
	3: "hsl(var(--color-yellow-3) / <alpha-value>)",
	4: "hsl(var(--color-yellow-4) / <alpha-value>)",
	5: "hsl(var(--color-yellow-5) / <alpha-value>)",
	6: "hsl(var(--color-yellow-6) / <alpha-value>)",
	7: "hsl(var(--color-yellow-7) / <alpha-value>)",
	8: "hsl(var(--color-yellow-8) / <alpha-value>)",
	9: "hsl(var(--color-yellow-9) / <alpha-value>)",
	10: "hsl(var(--color-yellow-10) / <alpha-value>)",
	11: "hsl(var(--color-yellow-11) / <alpha-value>)",
	12: "hsl(var(--color-yellow-12) / <alpha-value>)",
};
export const yellowA = {
	1: "hsl(var(--color-yellowA-1))",
	2: "hsl(var(--color-yellowA-2))",
	3: "hsl(var(--color-yellowA-3))",
	4: "hsl(var(--color-yellowA-4))",
	5: "hsl(var(--color-yellowA-5))",
	6: "hsl(var(--color-yellowA-6))",
	7: "hsl(var(--color-yellowA-7))",
	8: "hsl(var(--color-yellowA-8))",
	9: "hsl(var(--color-yellowA-9))",
	10: "hsl(var(--color-yellowA-10))",
	11: "hsl(var(--color-yellowA-11))",
	12: "hsl(var(--color-yellowA-12))",
};
